node index.js DK
node index.js FI
node index.js SV-FI
node index.js FR
node index.js DE
node index.js GB
node index.js IT
node index.js MX
node index.js NO
node index.js ES
node index.js SE
node index.js NL